language: node_js
node_js:
- '5'
- '5.1'
- '4'
- '4.2'
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- '0.8'
- '0.6'
- iojs
deploy:
  provider: openshift
  user: jdamor.juampi@gmail.com
  password:
    secure: hxqaRkoFI0rt4lk5ZEKPytoRPnCJa3UP4vcb6REfjRDGNP6i4CuFJSWLOY0qq3rqu3l4Sg0YwqV+2A28kIThVsaRizpwYDPe7tHwA36OwI0Kc5ryxkkPkgWlk1tX8vYm/4+pPb2eoKguaVImn5Prpt28MeQyiSuZY88eXHbkLxCv+E5JX4bOph9OXxZk/HGu2n9QlmOKnxfn8sFa1UoU736SShIVtvwLrX9XQfd3KGhZzc6kSDfuhacPn4OhZLKqwZUmXS7wM+6ctWaQ+dGsqVdPcWkwMxxRx9SHTySna3LgHdLw+3sd39Js4IUSUR8dwuJ1azGF+GHJlO6LHUBoCitfaea7uiI5aM8ErLdou4oqVBqUN53yO66vY4GRmO21UuKI7FkQGC08s2QVsxtqTm7gjdIU40eijfBW8Ozwst1TuifzHZ6D/3J3hQYA7ynpzYPe3g/eC9ffmETMlN//9SnfS5zpUJTaV0Srhr23bFmF2NEXkD0RAhmJbKSexAsFbm8bzVsOo4PNGWP0S3A5goQ1X+4jbmroEqT/G+D5ytPZs2JdDNf4xE0y+tNne2aBcof9sW0DhrMaLOQhcF+RKp9ISo8QImwBS6o05zhOsqTDXCdDJURHAmuo91Z1d+F+ofWYZXGbKEmsQuTJKkt9llzh7mr/APzdiYM15RavZxA=
  app: restjs
  domain: jdamor
  on:
    repo: jdamor/nodejs-rest-openshift
