language: node_js
node_js:
- stable
deploy:
  provider: openshift
  user: jdamor.juampi@gmail.com
  password:
    secure: L/ViTHP3vIPLV7zvU9s/R8WlTN2lY9qhY/FkzC/5Vuh5mYNBRlrLUcxjMl4s5Ezo8HkdrlQIXPS4n4qbul7seIjmShwOiLGMSdJM0SVZZX5i9p0EJv9AJLfA6UDuRSs3OQE2PvcvbsiaEaQxkM3W3kMn61g1h541MjyeUNadCRsm12XcdwISKM3ia0aD0RQVmF/7fjOEv9T/sLKyv4u4VZxQ0ZzdbGS31kDuaaEpimsaej8eplPyhutGme8SnK3Tfl4Ku06ewfWjOxlyCkXdnG71/GMiRl75mG0mHpQxf49vjDcOF8EjerS0ZmZoQ9FexZs4Sa+dDy9zvaqO686UjUnOaDR9rd4wBUPPoZIc9yL3ZwPmKGq1etKrR/ng/Ohlkyy70szehegjE1J044GVyceMjICEQ6v17YHNkDCmJBkB9MA+07W3nu+mfwmL38rqUs+Q/FMBk90F5ydooOatBzJx3BrBaGIkhkE0X6UMT8jUVWGQqdZ92J8FPlx4U05DLWd1s/J9b4b28LT/XQNcWaPJOAxYfRnTAH0yPKxGfo/i28aawgyTlP32Kr/rBdzQELXUcHrWUhDuIgVHTmwGAAeoT6Rk5FOolvYtYFo+G4DbCtb0ElnFizr6UY6I7RC24XXbh/z+4Al46k/4TRSt/Fm1tGU5MIzRPthjGV9T+ic=
  app: nodejs-rest-openshift
  domain: jdamor
  on:
    repo: jdamor/nodejs-rest-openshift
